name: photomnemonic
#
on:
  push:
    branches:
    paths-ignore: ["README.md"]
  workflow_dispatch:
env:
  containerName: photomnemonic

jobs:
  turkeyGitops:
    uses: Hubs-Foundation/hubs-ops/.github/workflows/turkeyGitops.yml@master
    with:
      registry: hubsfoundation
      push_gcr: true
      # dockerfile: Dockerfile
    secrets:
      DOCKER_HUB_PWD: ${{ secrets.DOCKER_HUB_PWD }}
      GCP_TURKEYGITOPS_SA_JSON: ${{ secrets.GCP_TURKEYGITOPS_SA_JSON }}
